### ISSUE TITLE
SSR Broken

### ISSUE THREAD

**Issue by anthony0030** [acidb/mobiscroll#477]
Version 4.10.4 no longer works with SSR, If you need more info please feel free to contact me.

Using browser-only version of superagent in non-browser environment

/Users/anthonyveaudry/Sites/gothassos-react/node_modules/@mobiscroll/react/dist/js/mobiscroll.react.min.js:2
 ...                                                                                                                                                                      ^
ReferenceError: document is not defined
    at /Users/anthonyveaudry/Sites/gothassos-react/node_modules/@mobiscroll/react/dist/js/mobiscroll.react.min.js:2:58483
    at /Users/anthonyveaudry/Sites/gothassos-react/node_modules/@mobiscroll/react/dist/js/mobiscroll.react.min.js:2:84
    at Object.<anonymous> (/Users/anthonyveaudry/Sites/gothassos-react/node_modules/@mobiscroll/react/dist/js/mobiscroll.react.min.js:2:287)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

**Comment by anthony0030** [comment]
I upgraded to 5.0.0-beta2 and it doesn't have this problem

**Comment by dioslaska** [comment]
Thanks for reporting, we will fix this in v4 as well in the next bugfix release.

**Comment by anthony0030** [comment]
@mobiscroll/react version 4.10.5 is working now :)

Thank you Mobiscroll team!

**Comment by dioslaska** [comment]
Thanks for confirming!
